[build]
  command = "npm run build"  # Replace with your build command if needed
  functions = "serverless/functions"  # Replace with your serverless functions folder

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"  # Adjust based on your serverless function file

[context.production]
  [context.production.environment]
    NODE_ENV = "production"
  [context.production.headers]
    Cache-Control = "public, max-age=0, must-revalidate"
 